services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-api_db}

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: donperez/fastapi_items
    restart: always
    environment:
      - POSTGRES_SERVER=db
    ports:
      - 8080:8000
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app

