services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: donperez/fastapi_items
    restart: always
    environment:
      - POSTGRES_SERVER=db
    ports:
      - 8080:8000
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app

